### PR TITLE
Update 0707-sys-admin-nala_de.md

### PR DESCRIPTION
**Pull request by hhl**
Mention the changes about full-upgrade

### CODE REVIEW

**Review by fethomm — APPROVED** [review]

**Comment by hhl** [comment]
@fethomm, please check the translation too

**Review by fethomm — CHANGES_REQUESTED** [review]
In line 34, 'update' should be 'upgrade'

**Comment by hhl** [comment]
Mh, I am not sure, **nala upgrade --no-full** is the same as **apt upgrade**?

So I wrote **upgrade** instead of **update**.

**Comment by hhl** [comment]
ah sorry, now I understand

**Comment by hhl** [comment]
@ak-li we should merge it ASAP and update the online manual too, also the installed one (build a new package), this is an important change!

All other pending changes have time.

**Comment by ak-li** [comment]
In 0707-..._de  
Habe den Text zusammengefasst, die meiner Meinung nach korrekten nala Befehle eingetragen und unsere Formatkonventionen angewendet.  

Die Änderungen an der en Version machen wir im WIP Branch.

**Comment by hhl** [comment]
done

**Pull request merged**
